### ISSUE TITLE
Open Hardware ROS2 robot

### ISSUE THREAD

**Issue by samuk** [Reinbert/ros_esp32cam_diffdrive#1]
@Reinbert does participating in this project https://cloud.transition-space.org/apps/onlyoffice/s/KyTnsYjs4GRkXjZ seem interesting? Your existing code already looks useful for the project.

Rough idea stage at the moment, but a few people are interested. In my more grandiose moments, I imagine it could become the Turtlebot of uRos.

**Comment by Reinbert** [comment]
Do you have a less fishy file hosting solution?

**Comment by samuk** [comment]
Hmm not really. It's just Nextcloud & Onlyoffice. Guess I could attach file here when  at a computer tomorrow.

**Comment by samuk** [comment]
Here's a PDF copy [rosmo.pdf](https://github.com/Reinbert/ros_esp32cam_diffdrive/files/7519231/rosmo.pdf) just a bunch of ideas at the moment, but I have a few people interested in contributing.

**Comment by samuk** [comment]
I just spotted this ESP32 cam robot and thought you might like it: 
https://www.tindie.com/products/bluino_electronics/wifi-robot-car-camera-kit-esp32-cam/

https://www.pcbway.com/project/shareproject/ESP32_Cam_Motor_Driver_Shield_L293D.html
